services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      retries: 5
      start_period: 5s

  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:8000 app:app"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_APP: app:app
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
