services:
  - type: web
    name: faktury-elen
    env: docker
    plan: free
    region: frankfurt
    # Brak dockerCommand -> Render użyje CMD z Dockerfile
    envVars:
      - key: FLASK_APP
        value: app:app
      - key: SECRET_KEY
        value: "5a39f36d12a2b7b098e22b9677978d24ba683d9b54db365e5a18be1125438592"
      - key: DATABASE_URL
        fromDatabase:
          name: faktury-db
          property: connectionString

databases:
  - name: faktury-db
    databaseName: faktury
    plan: free
    region: frankfurt
